kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: grafana
spec:
  rules:
    - host: grafana.MYDOMAIN.COM
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: 3000
