kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-backup
  labels:
    app: mongo-backup
spec:
  storageClassName: nfs-client
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteMany
