# TODO: Support more replicas
apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init-replica
spec:
  template:
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: arm64
      containers:
        - name: mongo-sidecar
          image: mongo:4
          command:
            - bash
            - -c
            - |
              for i in `seq 1 30`; do \
                mongo mongo-0.mongo.public/rocketchat --eval \
                'rs.initiate({ _id: "rs0", members: [ { _id: 0, host: "mongo-0.mongo.public:27017" }, { _id: 1, host: "mongo-1.mongo.public:27017" }  ]})' && \
                s=$$? && break || s=$$?; echo "Tried $$i times. Waiting 5 secs..."; sleep 5; done; (exit $$s)
      restartPolicy: OnFailure
  backoffLimit: 8
