kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: docker-registry
  annotations:
    # kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: docker.MYDOMAIN.COM
      http:
        paths:
          - path: /
            backend:
              serviceName: docker-registry
              servicePort: 5000
